[package]
name = "comfy_script_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
nom = "7.1.3"
nom_locate = "4.2.0"
